# Generated by Django 4.0.2 on 2022-08-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_tutorial_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('professional', models.CharField(default='', max_length=30)),
                ('age', models.CharField(blank=True, default='', max_length=3)),
            ],
        ),
    ]
